service: slack-time-translation

custom:
  defaultAccount: dummy
  defaultDigest: dummy
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 20
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    ${file(./env.yml)}

functions:
  command:
    handler: command
    events:
      - http:
          path: command
          method: post
