org: qazx7412
app: slack-time-translation
service: slack-time-translation

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 20
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/amd64
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    ${file(./env.yml)}

functions:
  command:
    image:
      name: appImage
      command:
        - command
    events:
      - http:
          path: command
          method: post
